# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Compile
        run: go build -o gocacheprog github.com/cox96de/gocacheprog/cmd/gocacheprog

      - name: Test with disk cache
        run: docker run --rm -v $PWD:/app -w /app/cmd/gocacheprog -e "GOCACHEPROG=/app/gocacheprog --cache=disk --disk-dir=/root/.cache/go-build/gocacheprog" cox96de/golang:gocacheprog  go build -o main .
