# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build Go
        run: docker build -t golang:dev -f go.Dockerfile .

      - name: Compile
        run: go build -o gocacheprog github.com/cox96de/gocacheprog/cmd/gocacheprog

      - name: Test
        run: docker run --rm -v $PWD:/app -w /app/cmd/gocacheprog -e GOCACHEPROG=/app/gocacheprog golang:dev go build -o main .

